[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#1c1c1f"
foreground = "#CDD6F4"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.offset]
x = -1
y = 6

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_padding = false
opacity = 0.96

[window.padding]
x = 24
y = 8

[keyboard]